[build]
  publish = "."
  functions = "netlify/functions"

# ✅ Force public access for PWA files
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200

# ✅ Fallback rule for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
