[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
